name: powersync-prod

services:
  server:
    container_name: powersync-server
    build:
      context: ../
      dockerfile: server/Dockerfile
    restart: always
    volumes:
      - ./secrets:/app/secrets
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - 4040:4040
    healthcheck:
      disable: false

  grafana-alloy:
    container_name: powersync-grafana-alloy
    image: grafana/alloy:latest
    volumes:
      - ./config/grafana-alloy.config.hcl:/etc/alloy/config.alloy
    env_file:
      - ./secrets/grafana-credentials.env
    command: ["run", "/etc/alloy/config.alloy"]
    restart: unless-stopped
    depends_on:
      - server
