name: powersync-prod

services:
  server:
    container_name: powersync-server
    build:
      context: ../
      dockerfile: server/Dockerfile
    restart: always
    volumes:
      - ./secrets:/app/secrets
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - 4040:4040
    healthcheck:
      disable: false
